#include <stdlib.h>
#include <stdio.h> 
#include <mpi.h>
#include <omp.h>

//method used to calculate the first row, last row and the total number of rows of each MPI Task
void set_parameters(int rank, int size, long world_size, long * first_row, long * last_row, long * local_rows )
{  
  *local_rows = world_size%size-rank <= 0 ? (long)(world_size/size) : (long)(world_size/size)+1;
  *first_row = world_size%size-rank >= 0 ? rank*(long)(world_size/size)+rank : rank*(long)(world_size/size)+world_size%size;
  *last_row = (*first_row)+(*local_rows)-1;

}

//Test method (print all the local world)
void write_pgm_image_test( void *image, int maxval, int xsize, int ysize, const char *image_name)
{
  FILE* image_file; 
  image_file = fopen(image_name, "w"); 
  
  int color_depth = 1 + ( maxval > 255 );

  fprintf(image_file, "P5\n# generated by\n# Filippo Olivo\n%d %d\n%d\n", xsize, ysize, maxval);

  fwrite( image, 1, xsize*ysize*color_depth, image_file);  

  fclose(image_file); 
  return ;

}

void write_pgm_image( unsigned char *image, int maxval, long xsize, long ysize, const char *image_name, int rank, int size)
{

  int color_depth = 1 + ( maxval > 255 );
  FILE* image_file; 
  char * file_name = (char *)malloc(60);

  sprintf(file_name, "%s_%03d_%03d_%03d.pgm",image_name,size,omp_get_max_threads(),rank);
  image_file = fopen(file_name, "w"); 

  if(rank == 0){
    fprintf(image_file, "P5\n# generated by\n# Filippo Olivo\n%d %d\n%d\n", xsize, xsize, maxval);
  }
  
  fwrite( &image[xsize], 1, xsize*ysize*color_depth, image_file); 
  fclose(image_file);
  
  free(file_name);

  return ;
}

void read_pgm_image( unsigned char **image, int *maxval, long *local_rows, long *world_size, 
                    const char *image_name, int rank, int size, MPI_Status * s, MPI_Request * r){
  int off  = 0;
  MPI_Status status;
    long first_row, last_row;
  if(rank == 0){
  FILE* image_file; 
  image_file = fopen(image_name, "r"); 

  *image = NULL;
  *world_size = *local_rows = *maxval = 0;

  char    MagicN[2];
  char   *line = NULL;
  size_t  k, n = 0;


  k = fscanf(image_file, "%2s%*c", MagicN );
  off += k;

  k = getline( &line, &n, image_file);
  off+=k;

  while ( (k > 0) && (line[0]=='#') ){

  k = getline( &line, &n, image_file);
  off+=k;

  }

  long temp;
  if (k > 0)
    {
      k = sscanf(line, "%ld%*c%ld%*c%d%*c", &temp, world_size, maxval);
      if ( k < 3 )
	    k = getline(&line,&n,image_file);
      off+=k;
      k = sscanf(line, "%d%*c", maxval);
    }
  else
    {
      *maxval = -1;
      free( line );
      return;
    }
      fclose(image_file);
      free(line);
  }
  MPI_Bcast(&off,1,MPI_INT,0,MPI_COMM_WORLD);
  MPI_Bcast(world_size,1,MPI_LONG,0,MPI_COMM_WORLD);

  set_parameters(rank, size,*world_size, &first_row, &last_row, local_rows);  
  int color_depth = 1 + ( *maxval > 255 );
  
  MPI_File fh;
  MPI_File_open(MPI_COMM_WORLD, image_name, MPI_MODE_RDONLY,
                MPI_INFO_NULL, &fh);  
  unsigned int to_read_size = (*world_size) * (*local_rows) * color_depth;
  MPI_File_seek(fh, off+2+first_row**world_size, MPI_SEEK_CUR);

  if ( (*image = (unsigned char  *)malloc( (*local_rows+2)*(*world_size)*sizeof(unsigned char))) == NULL )
    {
      return;
    }
  unsigned char * v = *image;
  MPI_File_read(fh, &v[*world_size], to_read_size, MPI_UNSIGNED_CHAR, &status);
  MPI_Barrier(MPI_COMM_WORLD);
  return;
}